### ISSUE TITLE
TruffleHog CI/CD Action

### ISSUE THREAD

**Issue by Twonki** [Twonki/Microtope#103]
[TruffleHog](https://github.com/dxa4481/truffleHog) is a known python-program to check for secrets in Code. It would be nice to check the code with trufflehog in every PR to not introduce new secrets (if any). 

**Proposed Solution**
A docker container which should: 
- Install Pip & Trufflehog
- Install Git and pull Repository (the full)
- Run Trufflehog (With certain files excepted)
- Fail (the container) if Trufflehog finds any secrets.

Then: 
- Make a github action to run the container
- impement the github action on EVERY pr

**Alternatives:**
There are actually many tools such as trufflehog on the opensource-market, 

But TruffleHog has a lot of functionalty needed and seems quite easy to use. 

**Additional Context**

[Trufflehog repository](https://github.com/dxa4481/truffleHog)

If done after #100 it can be added to the same github action. 

This would be maybe a mighty by-product to contribute to github actions.

**Comment by Twonki** [comment]
There is already an Action @ https://github.com/ChristianWitts/actions/tree/master/truffleHog 

Maybe this can be used with/after migrating it. See https://github.com/actions/migrate

**Comment by Twonki** [comment]
Another Action would be https://github.com/eshork/gitleaks-action 

Maybe do both? Does that make sense?

**Comment by Twonki** [comment]
Another one: https://github.com/marketplace/actions/secret-scan

**Comment by MuhaddiMu** [comment]
> There is already an Action @ https://github.com/ChristianWitts/actions/tree/master/truffleHog
> Maybe this can be used with/after migrating it. See https://github.com/actions/migrate


Did you implement that? I can't see. If you did please let me know. I'm having trouble adding this workflow. I really like the automation you have implemented overall in this project 👍

**Comment by Twonki** [comment]
Hi @MuhaddiMu , thanks for reaching out! 
I have not got it running, i am currently a little limited by my mobile machine, and working with a docker compose is just too painfull :( 

You might want to look into [This Secret-Scanner](https://github.com/cds-snc/github-actions/tree/master/seekret) , I found it under [Awesome Actions](https://github.com/sdras/awesome-actions) which seem to be properly maintained. 

It might helps you if you can run your [Action Locally](https://github.com/nektos/act). 

Also you should be able to run the docker-containers manually used by the actions. When they run on your machine, you can step by step play in them until you see results (or get depressed). 

Keep me updated! Maybe we can figure this out together!

**Comment by MuhaddiMu** [comment]
Hi @Twonki, Thank you for your response.

That makes sense. Currently, I go with the https://github.com/eshork/gitleaks-action

I implemented the TruffleHog as a custom GitHub check but unfortunately, it doesn't show any output on the console. I tried running it locally, it shows output and works perfectly but not on the GitHub itself. I don't know what I am missing out there. Below is my action configuration:

```
name: Credentials Check

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: '3.6'
    - name: Security Check with TruffleHog
      run: |
        pip install trufflehog
        
        wget -O regex.json https://raw.githubusercontent.com/dxa4481/truffleHogRegexes/master/truffleHogRegexes/regexes.json
        
        trufflehog --regex --rules regex.json --entropy=False ./

        rm regex.json
```
